/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeDemoRouteImport } from './routes/theme-demo'
import { Route as TestPhase3RouteImport } from './routes/test-phase3'
import { Route as TestOnboardingRouteImport } from './routes/test-onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as Phase3DemoRouteImport } from './routes/phase3-demo'
import { Route as LoadingDemoRouteImport } from './routes/loading-demo'
import { Route as DemoAnimationsRouteImport } from './routes/demo-animations'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoesIndexRouteImport } from './routes/shoes.index'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ShoesNewRouteImport } from './routes/shoes.new'
import { Route as ShoesShoeIdRouteImport } from './routes/shoes.$shoeId'
import { Route as RunsNewRouteImport } from './routes/runs.new'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as CollectionsNewRouteImport } from './routes/collections.new'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as ShoesShoeIdEditRouteImport } from './routes/shoes.$shoeId.edit'
import { Route as RunsRunIdEditRouteImport } from './routes/runs.$runId.edit'
import { Route as CollectionsCollectionIdEditRouteImport } from './routes/collections.$collectionId.edit'

const ThemeDemoRoute = ThemeDemoRouteImport.update({
  id: '/theme-demo',
  path: '/theme-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPhase3Route = TestPhase3RouteImport.update({
  id: '/test-phase3',
  path: '/test-phase3',
  getParentRoute: () => rootRouteImport,
} as any)
const TestOnboardingRoute = TestOnboardingRouteImport.update({
  id: '/test-onboarding',
  path: '/test-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase3DemoRoute = Phase3DemoRouteImport.update({
  id: '/phase3-demo',
  path: '/phase3-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingDemoRoute = LoadingDemoRouteImport.update({
  id: '/loading-demo',
  path: '/loading-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAnimationsRoute = DemoAnimationsRouteImport.update({
  id: '/demo-animations',
  path: '/demo-animations',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesIndexRoute = ShoesIndexRouteImport.update({
  id: '/shoes/',
  path: '/shoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesNewRoute = ShoesNewRouteImport.update({
  id: '/shoes/new',
  path: '/shoes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesShoeIdRoute = ShoesShoeIdRouteImport.update({
  id: '/shoes/$shoeId',
  path: '/shoes/$shoeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsNewRoute = CollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesShoeIdEditRoute = ShoesShoeIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ShoesShoeIdRoute,
} as any)
const RunsRunIdEditRoute = RunsRunIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RunsRunIdRoute,
} as any)
const CollectionsCollectionIdEditRoute =
  CollectionsCollectionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => CollectionsCollectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/debug': typeof DebugRoute
  '/demo-animations': typeof DemoAnimationsRoute
  '/loading-demo': typeof LoadingDemoRoute
  '/phase3-demo': typeof Phase3DemoRoute
  '/profile': typeof ProfileRoute
  '/test-onboarding': typeof TestOnboardingRoute
  '/test-phase3': typeof TestPhase3Route
  '/theme-demo': typeof ThemeDemoRoute
  '/auth/signin': typeof AuthSigninRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteWithChildren
  '/collections/new': typeof CollectionsNewRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/shoes/$shoeId': typeof ShoesShoeIdRouteWithChildren
  '/shoes/new': typeof ShoesNewRoute
  '/collections': typeof CollectionsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/shoes': typeof ShoesIndexRoute
  '/collections/$collectionId/edit': typeof CollectionsCollectionIdEditRoute
  '/runs/$runId/edit': typeof RunsRunIdEditRoute
  '/shoes/$shoeId/edit': typeof ShoesShoeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/debug': typeof DebugRoute
  '/demo-animations': typeof DemoAnimationsRoute
  '/loading-demo': typeof LoadingDemoRoute
  '/phase3-demo': typeof Phase3DemoRoute
  '/profile': typeof ProfileRoute
  '/test-onboarding': typeof TestOnboardingRoute
  '/test-phase3': typeof TestPhase3Route
  '/theme-demo': typeof ThemeDemoRoute
  '/auth/signin': typeof AuthSigninRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteWithChildren
  '/collections/new': typeof CollectionsNewRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/shoes/$shoeId': typeof ShoesShoeIdRouteWithChildren
  '/shoes/new': typeof ShoesNewRoute
  '/collections': typeof CollectionsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/shoes': typeof ShoesIndexRoute
  '/collections/$collectionId/edit': typeof CollectionsCollectionIdEditRoute
  '/runs/$runId/edit': typeof RunsRunIdEditRoute
  '/shoes/$shoeId/edit': typeof ShoesShoeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/debug': typeof DebugRoute
  '/demo-animations': typeof DemoAnimationsRoute
  '/loading-demo': typeof LoadingDemoRoute
  '/phase3-demo': typeof Phase3DemoRoute
  '/profile': typeof ProfileRoute
  '/test-onboarding': typeof TestOnboardingRoute
  '/test-phase3': typeof TestPhase3Route
  '/theme-demo': typeof ThemeDemoRoute
  '/auth/signin': typeof AuthSigninRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteWithChildren
  '/collections/new': typeof CollectionsNewRoute
  '/runs/$runId': typeof RunsRunIdRouteWithChildren
  '/runs/new': typeof RunsNewRoute
  '/shoes/$shoeId': typeof ShoesShoeIdRouteWithChildren
  '/shoes/new': typeof ShoesNewRoute
  '/collections/': typeof CollectionsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/shoes/': typeof ShoesIndexRoute
  '/collections/$collectionId/edit': typeof CollectionsCollectionIdEditRoute
  '/runs/$runId/edit': typeof RunsRunIdEditRoute
  '/shoes/$shoeId/edit': typeof ShoesShoeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/debug'
    | '/demo-animations'
    | '/loading-demo'
    | '/phase3-demo'
    | '/profile'
    | '/test-onboarding'
    | '/test-phase3'
    | '/theme-demo'
    | '/auth/signin'
    | '/collections/$collectionId'
    | '/collections/new'
    | '/runs/$runId'
    | '/runs/new'
    | '/shoes/$shoeId'
    | '/shoes/new'
    | '/collections'
    | '/runs'
    | '/shoes'
    | '/collections/$collectionId/edit'
    | '/runs/$runId/edit'
    | '/shoes/$shoeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/debug'
    | '/demo-animations'
    | '/loading-demo'
    | '/phase3-demo'
    | '/profile'
    | '/test-onboarding'
    | '/test-phase3'
    | '/theme-demo'
    | '/auth/signin'
    | '/collections/$collectionId'
    | '/collections/new'
    | '/runs/$runId'
    | '/runs/new'
    | '/shoes/$shoeId'
    | '/shoes/new'
    | '/collections'
    | '/runs'
    | '/shoes'
    | '/collections/$collectionId/edit'
    | '/runs/$runId/edit'
    | '/shoes/$shoeId/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/debug'
    | '/demo-animations'
    | '/loading-demo'
    | '/phase3-demo'
    | '/profile'
    | '/test-onboarding'
    | '/test-phase3'
    | '/theme-demo'
    | '/auth/signin'
    | '/collections/$collectionId'
    | '/collections/new'
    | '/runs/$runId'
    | '/runs/new'
    | '/shoes/$shoeId'
    | '/shoes/new'
    | '/collections/'
    | '/runs/'
    | '/shoes/'
    | '/collections/$collectionId/edit'
    | '/runs/$runId/edit'
    | '/shoes/$shoeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DebugRoute: typeof DebugRoute
  DemoAnimationsRoute: typeof DemoAnimationsRoute
  LoadingDemoRoute: typeof LoadingDemoRoute
  Phase3DemoRoute: typeof Phase3DemoRoute
  ProfileRoute: typeof ProfileRoute
  TestOnboardingRoute: typeof TestOnboardingRoute
  TestPhase3Route: typeof TestPhase3Route
  ThemeDemoRoute: typeof ThemeDemoRoute
  AuthSigninRoute: typeof AuthSigninRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRouteWithChildren
  CollectionsNewRoute: typeof CollectionsNewRoute
  RunsRunIdRoute: typeof RunsRunIdRouteWithChildren
  RunsNewRoute: typeof RunsNewRoute
  ShoesShoeIdRoute: typeof ShoesShoeIdRouteWithChildren
  ShoesNewRoute: typeof ShoesNewRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  ShoesIndexRoute: typeof ShoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-demo': {
      id: '/theme-demo'
      path: '/theme-demo'
      fullPath: '/theme-demo'
      preLoaderRoute: typeof ThemeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-phase3': {
      id: '/test-phase3'
      path: '/test-phase3'
      fullPath: '/test-phase3'
      preLoaderRoute: typeof TestPhase3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-onboarding': {
      id: '/test-onboarding'
      path: '/test-onboarding'
      fullPath: '/test-onboarding'
      preLoaderRoute: typeof TestOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase3-demo': {
      id: '/phase3-demo'
      path: '/phase3-demo'
      fullPath: '/phase3-demo'
      preLoaderRoute: typeof Phase3DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading-demo': {
      id: '/loading-demo'
      path: '/loading-demo'
      fullPath: '/loading-demo'
      preLoaderRoute: typeof LoadingDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-animations': {
      id: '/demo-animations'
      path: '/demo-animations'
      fullPath: '/demo-animations'
      preLoaderRoute: typeof DemoAnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes/': {
      id: '/shoes/'
      path: '/shoes'
      fullPath: '/shoes'
      preLoaderRoute: typeof ShoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes/new': {
      id: '/shoes/new'
      path: '/shoes/new'
      fullPath: '/shoes/new'
      preLoaderRoute: typeof ShoesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes/$shoeId': {
      id: '/shoes/$shoeId'
      path: '/shoes/$shoeId'
      fullPath: '/shoes/$shoeId'
      preLoaderRoute: typeof ShoesShoeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/new': {
      id: '/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof CollectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes/$shoeId/edit': {
      id: '/shoes/$shoeId/edit'
      path: '/edit'
      fullPath: '/shoes/$shoeId/edit'
      preLoaderRoute: typeof ShoesShoeIdEditRouteImport
      parentRoute: typeof ShoesShoeIdRoute
    }
    '/runs/$runId/edit': {
      id: '/runs/$runId/edit'
      path: '/edit'
      fullPath: '/runs/$runId/edit'
      preLoaderRoute: typeof RunsRunIdEditRouteImport
      parentRoute: typeof RunsRunIdRoute
    }
    '/collections/$collectionId/edit': {
      id: '/collections/$collectionId/edit'
      path: '/edit'
      fullPath: '/collections/$collectionId/edit'
      preLoaderRoute: typeof CollectionsCollectionIdEditRouteImport
      parentRoute: typeof CollectionsCollectionIdRoute
    }
  }
}

interface CollectionsCollectionIdRouteChildren {
  CollectionsCollectionIdEditRoute: typeof CollectionsCollectionIdEditRoute
}

const CollectionsCollectionIdRouteChildren: CollectionsCollectionIdRouteChildren =
  {
    CollectionsCollectionIdEditRoute: CollectionsCollectionIdEditRoute,
  }

const CollectionsCollectionIdRouteWithChildren =
  CollectionsCollectionIdRoute._addFileChildren(
    CollectionsCollectionIdRouteChildren,
  )

interface RunsRunIdRouteChildren {
  RunsRunIdEditRoute: typeof RunsRunIdEditRoute
}

const RunsRunIdRouteChildren: RunsRunIdRouteChildren = {
  RunsRunIdEditRoute: RunsRunIdEditRoute,
}

const RunsRunIdRouteWithChildren = RunsRunIdRoute._addFileChildren(
  RunsRunIdRouteChildren,
)

interface ShoesShoeIdRouteChildren {
  ShoesShoeIdEditRoute: typeof ShoesShoeIdEditRoute
}

const ShoesShoeIdRouteChildren: ShoesShoeIdRouteChildren = {
  ShoesShoeIdEditRoute: ShoesShoeIdEditRoute,
}

const ShoesShoeIdRouteWithChildren = ShoesShoeIdRoute._addFileChildren(
  ShoesShoeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DebugRoute: DebugRoute,
  DemoAnimationsRoute: DemoAnimationsRoute,
  LoadingDemoRoute: LoadingDemoRoute,
  Phase3DemoRoute: Phase3DemoRoute,
  ProfileRoute: ProfileRoute,
  TestOnboardingRoute: TestOnboardingRoute,
  TestPhase3Route: TestPhase3Route,
  ThemeDemoRoute: ThemeDemoRoute,
  AuthSigninRoute: AuthSigninRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRouteWithChildren,
  CollectionsNewRoute: CollectionsNewRoute,
  RunsRunIdRoute: RunsRunIdRouteWithChildren,
  RunsNewRoute: RunsNewRoute,
  ShoesShoeIdRoute: ShoesShoeIdRouteWithChildren,
  ShoesNewRoute: ShoesNewRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  ShoesIndexRoute: ShoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
