name: PWA Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  pwa-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build app
      run: bun run build

    - name: Install Lighthouse CI
      run: bun add -g @lhci/cli

    - name: Run Lighthouse CI
      run: |
        bun run pwa:serve &
        sleep 10
        lhci autorun --upload.target=temporary-public-storage
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

    - name: Upload PWA audit results
      uses: actions/upload-artifact@v3
      with:
        name: pwa-audit-results
        path: .lighthouseci/
